Add pathPrefix
IntegralSoftware/flysystem-pdo-adapter pull request #10
Opened 2018-11-02 14:14 UTC by EgorGruzdev

It is convenient to use when two Replicate Adapters are set on the same folder, but one of the adapters is set on the internal folder, i.e. the first dapter is built on '/test/' the second on '/test/test2'.
The same table is used.

2018-11-02 19:24 UTC, zaak requested changes
Hi @EgorGruzdev! Thanks for the PR, it's a cool idea. Although I think it would be good to add some additional check to keep the backward compatibility.

2018-11-02 19:24 UTC, zaak commented on src/PDOAdapter.php
>       * @param string $tableName
Please properly update the PHPDoc.

2018-11-02 19:24 UTC, zaak commented on src/PDOAdapter.php
> +        $tableName = isset($settings['tableName']) ? $settings['tableName'] : null;
I think it would be good to not break the backward compatibility here. Can we add some `is_string` check of the `$settings` argument and still use it as table name if it's `string`?

2018-11-02 21:21 UTC, EgorGruzdev commented on src/PDOAdapter.php
>       * @param string $tableName
Good, please view my new commit.
I have removed this property.

2018-11-02 21:21 UTC, EgorGruzdev commented on src/PDOAdapter.php
> +        $tableName = isset($settings['tableName']) ? $settings['tableName'] : null;
Good, backward compatibility.

2018-11-04 07:25 UTC, zaak approved these changes

2018-11-04 07:26 UTC, merged

2018-11-04 07:26 UTC, zaak commented
Thanks @EgorGruzdev!